title = 'Freifunk Berlin'
languageCode = 'de'

baseURL = "https://berlin.freifunk.net"
theme = "ananke"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

SectionPagesMenu = "main"
enableRobotsTXT = true

disableKinds = ['taxonomy', 'term']

[languages]
    [languages.de]
	weight = 1
        languageName = "Deutsch"
        languageCode = "de"
        title = "Freifunk Berlin"	
    [languages.en]
        weight = 2
        languageName = "English"
        languageCode = "en"
        title = "Freifunk Berlin"

[sitemap]
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "favicon.ico"
  site_logo = "logo.png"
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-white"
  # recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/freifunk_berlin"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/freifunk-berlin"

[menu]
[[menu.main]]
    name = 'freifunk.net'
    url = 'https://freifunk.net'
    weight = 8
    [menu.main.params]
      rel = 'external'
[[menu.main]]
    name = 'FAQ'
    url = 'https://wiki.freifunk.net/Berlin:FAQ'
    weight = 6
    [menu.main.params]
      rel = 'external'

[markup.goldmark.renderer]
unsafe = true
